 FROM node:21-alpine3.18

  WORKDIR /app

  COPY package.json .
  COPY package-lock.json .
  COPY tsconfig.json .
  COPY ecosystem.config.js .
  COPY .env.production .
  COPY ./src ./src

  RUN apk add python3
  RUN npm install pm2 -g
  RUN npm install -g npm@9.6.6
  RUN npm i -g
  RUN npm install --include=optional sharp
  RUN npm install --os=linux --libc=musl --cpu=x64 sharp
  COPY . .
  RUN npm run build

EXPOSE 3000

CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "production"]